### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by marcosdemelo** [smashah/wapi.js#1]
Hi @smashah, Do you intend to centralize WAPI.js maintenance here? How do you see it?

**Comment by smashah** [comment]
@marcosdemelo this whole project is at odds with the live patches structure of the main open-wa library which allows real time updates without the need to mess with dependencies and for that reason this project has been abandoned. If you need a working WhatsApp automation system then please consider using either open-wa or the alternative libraries that are being actively maintained.
